---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deploy
  labels:
    app: html-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app-httpd:base
        image: gcr.io/gupi-366622/hello-html-apache:base
        ports:
        - name: htmlapp-conport
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-app-svc
  labels:
    app: html-app
spec:
  type: LoadBalancer
  selector:
    app: html-app
  ports:
  - name: htmlapp-svcport
    port: 80
    protocol: TCP
    targetPort: htmlapp-conport
---